import Control from '@/app/Control'
import {Metadata} from 'next'
import Link from 'next/link'
import './globals.css'

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by ivory-code',
  icons: {
    icon: '/assets/images/ogu.webp',
  },
}

type TopicData = {
  id: number
  title: string
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/topics`)
  const topics = await res.json()

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic: TopicData) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            )
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  )
}
